In [352]:
import pandas as pd

In [353]:
df = pd.read_csv('covid_toy.csv')

In [354]:
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [355]:
print(df['cough'].unique())

['Mild' 'Strong']

In [356]:
df.isnull().sum()
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [357]:
df.shape

(100, 6)

In [358]:
from sklearn.model_selection import train_test_split

In [359]:
X = df.drop(columns=['has_covid'])
y = df['has_covid']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [360]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

In [361]:
transformer = ColumnTransformer(transformers=[
    ('tnf1' , SimpleImputer() , ['fever']) ,
    ('tnf2' , OrdinalEncoder(categories= [['Mild' , 'Strong']]) , ['cough']) ,
    ('tnf3' , OneHotEncoder(sparse_output =False , drop ='first') ,['city' , 'gender']) ], remainder='passthrough')

In [362]:
x_train_trans = transformer.fit_transform(x_train)

In [363]:
x_train_trans.shape

(80, 7)

In [364]:
x_test_trans = transformer.transform(x_test)

In [365]:
x_test_trans.shape

(20, 7)

In [366]:
feature_names = [
    'fever',
    'cough_encoded',
    'city_Delhi',
    'city_Kolkata',
    'city_Mumbai',
    'gender_Male',
    'age'
]
x_df = pd.DataFrame(x_train_trans, columns=feature_names)
display(x_df.head())

,fever,cough_encoded,city_Delhi,city_Kolkata,city_Mumbai,gender_Male,age
0,101.0,0.0,0.0,0.0,1.0,0.0,81.0
1,100.0,0.0,0.0,1.0,0.0,0.0,5.0
2,100.0,0.0,0.0,1.0,0.0,0.0,19.0
3,100.0,0.0,1.0,0.0,0.0,1.0,27.0
4,103.0,0.0,1.0,0.0,0.0,0.0,73.0

In [367]:

from sklearn.preprocessing import StandardScaler

In [368]:

scaler = StandardScaler()
x_train_scaler = scaler.fit_transform(x_train_trans)
x_test_scaler = scaler.transform(x_test_trans)

In [369]:

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

In [370]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train_scaler, y_train)

LogisticRegression(max_iter=1000)

In [371]:
y_predict = model.predict(x_test_scaler)

In [372]:
accuracy_score(y_test , y_predict)

0.45

In [373]:
print(y_predict)

['Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes']

In [374]:
print(y_test)

83     No
53    Yes
70     No
45     No
44     No
39     No
22    Yes
80    Yes
10     No
0      No
18    Yes
30    Yes
73    Yes
33     No
90     No
4      No
76    Yes
77     No
12     No
31     No
Name: has_covid, dtype: object