In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [6]:
df.shape

(8128, 5)

In [8]:
df['owner'].nunique()

5

In [13]:
df['fuel'].nunique()

4

In [17]:
##performing hotmodule using pandas get_dummies
#dropping first column to prevent multicollinearity( relationship among columns i.e one variable can be predicted by other) , impact model

df_encoded = pd.get_dummies(df  , columns=['fuel' , 'owner'] ,drop_first = True)

In [18]:
df_encoded

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [28]:
x_train , x_test , y_train  , y_test = train_test_split(df.iloc[ : , 0:4] , df.iloc[: ,-1] , test_size = 0.2 , random_state=2 )

In [39]:
ohe = OneHotEncoder(drop= 'first' , dtype= np.int32)
x_train_encoded = ohe.fit_transform(x_train[['fuel' , 'owner']]).toarray()
x_test_encoded = ohe.transform(x_test[['fuel' , 'owner']]).toarray()

In [41]:
## we splitted the brand and km_driven and then after encoding fuel and owner we merge using numpy hstack
x_train_final = np.hstack(( x_train[['brand' , 'km_driven']].values ,  x_train_encoded))

In [45]:
x_test_final = np.hstack(( x_test[['brand' , 'km_driven']].values , x_test_encoded))

In [48]:
print('Training data' , x_train_final.shape)

Training data (6502, 9)

In [49]:
print('Test data' , x_test_final.shape)

Test data (1626, 9)

In [60]:
## implementing cardinality - to group rare categories into 1 group ,reduces dimensions

brand_counts = df['brand'].value_counts()

In [61]:
df['brand'].nunique()

32

In [62]:
threshold = 100 
rare_brands = brand_counts[brand_counts <= threshold ].index

In [64]:
df['brand'] = df['brand'].replace(rare_brands , "unknown")

In [68]:
df['brand'].nunique()

13